name: Fun
main: me.Defracted.Main
version: "1.0.3"
author: Defracted7
api-version: "1.15"

commands:
  joke:
    description: "Throws some very stupid joke."

  fart:
    description: "Бзднуть люто..."
    permission: "fun.fart"

  me:
    description: "Выполняет РП действие с рандомным шансом успеха."
    usage: "/me <действие>"
